#include "afxcoll.h"

IMPLEMENT_DYNAMIC(CObList, CObject)
IMPLEMENT_DYNAMIC(CPtrList, CObject)
IMPLEMENT_DYNAMIC(CStringList, CObject)
IMPLEMENT_DYNAMIC(CMapPtrToPtr, CObject)
IMPLEMENT_DYNAMIC(CPtrArray, CObject)
IMPLEMENT_DYNAMIC(CStringArray, CObject)
IMPLEMENT_DYNAMIC(CByteArray, CObject)
IMPLEMENT_DYNAMIC(CWordArray, CObject)
IMPLEMENT_DYNAMIC(CDWordArray, CObject)
IMPLEMENT_DYNAMIC(CUIntArray, CObject)
