#include "eafxcoll.h"

EIMPLEMENT_DYNAMIC(ECObList, ECObject)
EIMPLEMENT_DYNAMIC(ECPtrList, ECObject)
EIMPLEMENT_DYNAMIC(ECStringList, ECObject)
EIMPLEMENT_DYNAMIC(ECMapPtrToPtr, ECObject)
EIMPLEMENT_DYNAMIC(ECPtrArray, ECObject)
EIMPLEMENT_DYNAMIC(ECStringArray, ECObject)
EIMPLEMENT_DYNAMIC(ECByteArray, ECObject)
EIMPLEMENT_DYNAMIC(ECWordArray, ECObject)
EIMPLEMENT_DYNAMIC(ECDWordArray, ECObject)
EIMPLEMENT_DYNAMIC(ECUIntArray, ECObject)
